version: '3'

services:
  frontend:
    env_file:
      .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - '8080:80'
